version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: jertanu_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: jertanu-dev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  minio:
    image: minio/minio
    ports:
      - "49000:9000"
      - "49001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
    name: postgres_data
  minio_data:

networks:
  postgres_network:
    name: postgres_network